//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUsingService.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.Lab04Soap")]
    public interface Lab04Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.Fraction Add(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.Fraction Subtraction(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.Fraction Multiplication(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.Fraction Division(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoneyConvert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal MoneyConvert(decimal x, WebUsingService.MyService.MoneyConvertEnum type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Factorial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long Factorial(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NPrimeNumbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] NPrimeNumbers(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsPrime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IsPrime(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MD5Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MD5Encrypt(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MD5FileEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MD5FileEncrypt(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHA1Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SHA1Encrypt(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SHA1FileEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SHA1FileEncrypt(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.Student[] GetStudents(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentsNameOrderbyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetStudentsNameOrderbyName(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeatherInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.City[] GetWeatherInfo();
        
        // CODEGEN: Generating message contract since message ChungThucSoapHeaderRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChungThucSoapHeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUsingService.MyService.ChungThucSoapHeaderResponse ChungThucSoapHeader(WebUsingService.MyService.ChungThucSoapHeaderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fraction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numeratorField;
        
        private int denominatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Numerator {
            get {
                return this.numeratorField;
            }
            set {
                this.numeratorField = value;
                this.RaisePropertyChanged("Numerator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Denominator {
            get {
                return this.denominatorField;
            }
            set {
                this.denominatorField = value;
                this.RaisePropertyChanged("Denominator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChungThuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WeatherInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tempField;
        
        private string conditionField;
        
        private string imageField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
                this.RaisePropertyChanged("Temp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("Condition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class City : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private WeatherInfo weatherField;
        
        private WeatherInfo[] weathersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WeatherInfo Weather {
            get {
                return this.weatherField;
            }
            set {
                this.weatherField = value;
                this.RaisePropertyChanged("Weather");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public WeatherInfo[] Weathers {
            get {
                return this.weathersField;
            }
            set {
                this.weathersField = value;
                this.RaisePropertyChanged("Weathers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MoneyConvertEnum {
        
        /// <remarks/>
        USD2VND,
        
        /// <remarks/>
        VND2USD,
        
        /// <remarks/>
        EUR2VND,
        
        /// <remarks/>
        VND2EUR,
        
        /// <remarks/>
        YP2VND,
        
        /// <remarks/>
        VND2YP,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChungThucSoapHeader", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChungThucSoapHeaderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebUsingService.MyService.ChungThuc ChungThuc;
        
        public ChungThucSoapHeaderRequest() {
        }
        
        public ChungThucSoapHeaderRequest(WebUsingService.MyService.ChungThuc ChungThuc) {
            this.ChungThuc = ChungThuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChungThucSoapHeaderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChungThucSoapHeaderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ChungThucSoapHeaderResult;
        
        public ChungThucSoapHeaderResponse() {
        }
        
        public ChungThucSoapHeaderResponse(string ChungThucSoapHeaderResult) {
            this.ChungThucSoapHeaderResult = ChungThucSoapHeaderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Lab04SoapChannel : WebUsingService.MyService.Lab04Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Lab04SoapClient : System.ServiceModel.ClientBase<WebUsingService.MyService.Lab04Soap>, WebUsingService.MyService.Lab04Soap {
        
        public Lab04SoapClient() {
        }
        
        public Lab04SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Lab04SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab04SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab04SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebUsingService.MyService.Fraction Add(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y) {
            return base.Channel.Add(x, y);
        }
        
        public WebUsingService.MyService.Fraction Subtraction(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y) {
            return base.Channel.Subtraction(x, y);
        }
        
        public WebUsingService.MyService.Fraction Multiplication(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y) {
            return base.Channel.Multiplication(x, y);
        }
        
        public WebUsingService.MyService.Fraction Division(WebUsingService.MyService.Fraction x, WebUsingService.MyService.Fraction y) {
            return base.Channel.Division(x, y);
        }
        
        public string GetClientIP() {
            return base.Channel.GetClientIP();
        }
        
        public decimal MoneyConvert(decimal x, WebUsingService.MyService.MoneyConvertEnum type) {
            return base.Channel.MoneyConvert(x, type);
        }
        
        public long Factorial(int x) {
            return base.Channel.Factorial(x);
        }
        
        public int[] NPrimeNumbers(int n) {
            return base.Channel.NPrimeNumbers(n);
        }
        
        public int IsPrime(int number) {
            return base.Channel.IsPrime(number);
        }
        
        public string MD5Encrypt(string s) {
            return base.Channel.MD5Encrypt(s);
        }
        
        public string MD5FileEncrypt(string path) {
            return base.Channel.MD5FileEncrypt(path);
        }
        
        public string SHA1Encrypt(string s) {
            return base.Channel.SHA1Encrypt(s);
        }
        
        public string SHA1FileEncrypt(string path) {
            return base.Channel.SHA1FileEncrypt(path);
        }
        
        public WebUsingService.MyService.Student[] GetStudents(string url) {
            return base.Channel.GetStudents(url);
        }
        
        public string[] GetStudentsNameOrderbyName(string url) {
            return base.Channel.GetStudentsNameOrderbyName(url);
        }
        
        public WebUsingService.MyService.City[] GetWeatherInfo() {
            return base.Channel.GetWeatherInfo();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUsingService.MyService.ChungThucSoapHeaderResponse WebUsingService.MyService.Lab04Soap.ChungThucSoapHeader(WebUsingService.MyService.ChungThucSoapHeaderRequest request) {
            return base.Channel.ChungThucSoapHeader(request);
        }
        
        public string ChungThucSoapHeader(WebUsingService.MyService.ChungThuc ChungThuc) {
            WebUsingService.MyService.ChungThucSoapHeaderRequest inValue = new WebUsingService.MyService.ChungThucSoapHeaderRequest();
            inValue.ChungThuc = ChungThuc;
            WebUsingService.MyService.ChungThucSoapHeaderResponse retVal = ((WebUsingService.MyService.Lab04Soap)(this)).ChungThucSoapHeader(inValue);
            return retVal.ChungThucSoapHeaderResult;
        }
    }
}
